# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    defaults:
      run:
        working-directory: ./cs2-randomizer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore 
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: cs2randomizer.zip
          path: /home/runner/work/cs2-randomizer/cs2-randomizer/cs2-randomizer/bin/Release/net8.0/*.*
      - name: create release
        uses: ncipollo/release-action@v1.14.0
        with: 
          artifacts: "cs2randomizer.zip"
          
            
      
    
